### ISSUE TITLE
[Feature Request]: MemgraphDB Connection Compatibility

### ISSUE THREAD

**Issue by Mattang-John** [apache/hop#2566]
### What would you like to happen?

I'd like to be able to use the Neo4j Connection in Hop to connect to a MemgraphDB Database.

https://memgraph.com/

### Issue Priority

Priority: 3

### Issue Component

Component: Neo4j

**Comment by bamaer** [comment]
just tested with the default `docker run` command as specified on the memgraph download page, with one additional parameter : `docker run -it -p 7687:7687 -p 7444:7444 -p 3000:3000 -e MEMGRAPH="--bolt-server-name-for-init=Neo4j/" memgraph/memgraph-platform`
in the Neo4j connection properties, the protocol needs to be changed to `bolt` instead of the default `neo4j`
tested with the beer graph workflow from the samples project. 
The `Neo4j index` and `Neo4j constraint` actions don't work, but that may be related to another issue (requires Neo4j Enterprise Edition) and should be tracked in a separate ticket. 
Keeping this ticket open until this is added to the docs.
