### ISSUE TITLE
[Task]: improve loading time for execution information perspective with large number of executions

### ISSUE THREAD

**Issue by bamaer** [apache/hop#2845]
### What needs to happen?

the execution information perspective is slow to load large numbers of executions and/or executions with large file sizes (e.g. when executed with Detailed or Row Level logging). 

Additionally: show a warning when a workflow or pipeline is executed with Detailed or Row Level logging, or provide an option to skip execution logging for Detailed or Row Level logging. 

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by mattcasters** [comment]
I think that for large logging text blocks it's just not going to work to store this in the execution state JSON.
There's no skipping the loading of individual fields when inflating a JSON file.
As such I think that in order to get your hands on the logging text we need to provide a separate method in `IExecutionInfoLocation` and we need to store the logging text in a separate file.
