### ISSUE TITLE
[Task]: replace findDatabase in Action Evaluate table content

### ISSUE THREAD

**Issue by hansva** [apache/hop#2848]
### What needs to happen?

replace findDatabase in Action Evaluate table content

### Issue Priority

Priority: 3

### Issue Component

Component: Actions, Component: Database

**Comment by nadment** [comment]
I can't find any use of the findDatabase method in this action?

Just a little memory leak optimization:
`try (Database db = new Database(this, this, connection)) {`

**Comment by hansva** [comment]
It's in the dialog class which might also not be the best spot.
[plugins/actions/evaluatetablecontent/src/main/java/org/apache/hop/workflow/actions/evaluatetablecontent/ActionEvalTableContentDialog.java](https://github.com/apache/hop/blob/f6a6bb467890c1082fca318dc71c253f76938ff8/plugins/actions/evaluatetablecontent/src/main/java/org/apache/hop/workflow/actions/evaluatetablecontent/ActionEvalTableContentDialog.java#L528)

and `DatabaseMeta loadDatabase(
      IHopMetadataProvider metadataProvider, String connectionName)` is also not variable aware and should be replaced with `findDatabase(String name, IVariables variables)`

**Comment by hansva** [comment]
I also noticed that a lot of them use the following to serialize to XML. 
`XmlHandler.addTagValue("connection", connection == null ? null : connection.getName()));` which will translate the variable to the actual database name upon serialization and will not store the variable name. So it may be more work than anticipated.

**Comment by hansva** [comment]
For now we could replace it by using a string to hold the connection name/variable and load the databaseMeta using that. No need to refactor the full xml in one go

**Comment by sramazzina** [comment]
@nadment I already all of the main database transforms in the past converting them to use HopMetadataProperty and connection specified by variables without any problem. If you want I can take care about that complete convertion. It would be nice to have everthing cleaned up because that will be the way to serialize/deserialize xml in the future.

**Comment by nadment** [comment]
@sramazzina I have done some too. It would indeed be nice to clean up everything but it is a big effort. We can start with the actions and transforms using databases first. There are already tasks in Github for each Xml cleanup to do.

**Comment by sramazzina** [comment]
Why not taking care about less transforms per milestone and do the work one at a time but do everything (connection via variables, use of HopMetadataProperty and bunch of integration tests)? We could start from the less critical let me say. I could help with this. The problem is that sometime using HopMetadataProperty requires a bit of code reworking but by adding some good tests we should be safe.

**Comment by nadment** [comment]
Merge pull request https://github.com/apache/hop/pull/2864
