### ISSUE TITLE
[Task]: Update ivy dependency to reduce CVE impact

### ISSUE THREAD

**Issue by hansva** [apache/hop#3269]
### What needs to happen?

Update ivy to 2.5.2

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue

**Comment by ricozen** [comment]
Hi, 
First, thanks for the great work done on HOP !
We use HOP in docker images and we check their vulnerabilities with Trivy v0.44
This issue is reported as critical because of the [cve-2022-37865](https://avd.aquasec.com/nvd/2022/cve-2022-37865/) and high because of the [cve-2022-37866](https://avd.aquasec.com/nvd/2022/cve-2022-37866/) and [cve-2022-46751](https://avd.aquasec.com/nvd/2022/cve-2022-46751/).
**Trivy suggests to move at least to 2.5.2**
Our corp is quite fussy about security issues...
Would it be possible to make the update in the next release please ?
Regards

**Comment by hansva** [comment]
We are in the process of creating the next release, one of the final steps we do is a trivy scan and try to upgrade all we can. In some cases we are unable to do so because of 3rd party dependencies. Will give give an update here if this one is resolved
