### ISSUE TITLE
[Bug]: Import from Kettle - Get System Info -> transformation name / pipeline name error

### ISSUE THREAD

**Issue by Fjelley85** [apache/hop#3574]
### Apache Hop version?

2.7.0

### Java version?

11.0.19

### Operating system

Windows

### What happened?

When Importing from Kettle, the Transformation name / pipeline name output from Get System info gives <null> values.
![screenshot3](https://github.com/apache/hop/assets/10757859/030f6ed5-e3a8-4b0b-95aa-a3cc78dc6b08)

### Issue Priority

Priority: 2

### Issue Component

Component: Import, Component: Transforms

**Comment by sramazzina** [comment]
Hi @Fjelley85 I tried to reproduce your issue using Apache Hop 2.8 but everything is working perfectly. Can you try once again with Hop 2.8 and let me know? In case of any error, can you please post the kettle transformation that, when migrated, gives you the problem you reported so that we can analyze it better?

**Comment by Fjelley85** [comment]
Seems ok now
