### ISSUE TITLE
[Bug]: DuckDB - Explorer shows multiple entries for schemas. Tables and Views not populated in their sections. 

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#3666]
### Apache Hop version?

2.8-SNAPSHOT

### Java version?

11

### Operating system

Windows

### What happened?

![image](https://github.com/apache/hop/assets/1233654/f794dc8b-63a9-4f7c-93b3-cb7a472ed7f3)

### Issue Priority

Priority: 3

### Issue Component

Component: Database

**Comment by sramazzina** [comment]
@usbrandon we are going to see three different entries per schema name because we have the same set of schema for every catalog defined in DuckDB. In this case, we have 3 catalogs (because is a brand new DuckDB installation) and each catalog has 3 identically named schemas. THis is the reason why you are seeing 3 entries per schema name.

Therefore, apart from an overall improvement to the Database Explorer dialog, in this case a very quick solution could be to disambiguate the schema name by prepending the catalog name. That could be an easy option to better contextualize the things. Let me know what you thing about this.

@hansva @bamaer

**Comment by sramazzina** [comment]
@usbrandon @hansva @bamaer something like this?

![image](https://github.com/apache/hop/assets/1270945/4894259e-0a06-4b11-99f2-a5eae48974ee)

**Comment by sramazzina** [comment]
@usbrandon @hansva @bamaer Further refinement...

![image](https://github.com/apache/hop/assets/1270945/614bf9fd-fce7-4aa9-87c7-336fa2aea25b)

**Comment by hansva** [comment]
LGTM!
